### ISSUE TITLE
resizing main menu causes misalignment

### ISSUE THREAD

**Issue by jeltedeproft** [jeltedeproft/Norii#1]
when resizing the screen at the main menu, the clicklisteners are out of sync with the map
<img width="445" alt="Screenshot 2019-10-05 11 28 23" src="https://user-images.githubusercontent.com/22193978/66253095-52e48f80-e763-11e9-8559-e7727445de22.png">

**Comment by hazeliao** [comment]
Can I try to fix this for my Hacktoberfest commit?
