### ISSUE TITLE
resize with actions menu open

### ISSUE THREAD

**Issue by jeltedeproft** [jeltedeproft/Norii#13]
**Describe the bug**
When the actions menu is visible and the screen gets resized, the actions menu's position after the resize is not correct anymore.

**To Reproduce**
1. Start game
2. Place all 4 characters
3. Actions menu should now be visible
4. Resize

**Expected behavior**
Actions menu should relocate to the new position of the character

**Screenshots**
<img width="563" alt="Screenshot 2019-10-08 15 88 32" src="https://user-images.githubusercontent.com/22193978/66828827-4970d980-ef52-11e9-9ef6-1ab1e124dd76.png">

**Comment by Immutablevoid** [comment]
Hi, I was looking through issues to work on and came upon this one. I was wondering why not make the window non resizable.

Here are some of my reason why:
- Less effort to implement
- Usually games aren't resizable (if they are, they usually provide the dimensions)

This problem can also happen on other entities. For example on the main menu screen, if you resize the window the text and buttons become stretch.

If you make the window non resizable this will also fix these problems.

**Comment by jeltedeproft** [comment]
@ImmutableBox  hmm yeah in hindsight it might have been better to do that, it would solve a lot of problems. I just personally didnt like that.

At this point almost all resize bugs are fixed, so I'm not going back now.

**Comment by jeltedeproft** [comment]
fixed in one of my previous commits
