### ISSUE TITLE
resizing the game while in the battle screen crashes the game

### ISSUE THREAD

**Issue by jeltedeproft** [jeltedeproft/Norii#2]
this gives the following error

<img width="572" alt="Screenshot 2019-10-05 11 29 23" src="https://user-images.githubusercontent.com/22193978/66253114-95a66780-e763-11e9-8f3a-82c5dab6c09b.png">

**Comment by hazeliao** [comment]
Can I be assigned to fix this issue? @jeltedeproft

**Comment by jeltedeproft** [comment]
@hazeliao yeah sure, I appreciate the help. If more information is required let me know.
