### ISSUE TITLE
Pressing escape should open up a menu, which allows to go back to the main menu, change settings (not available yet), ...

### ISSUE THREAD

**Issue by jeltedeproft** [jeltedeproft/Norii#8]
Not high priority, just something nice to make it feel more complete

A nice clean menu, in an artstyle that doesn't feel out of place.

**Comment by Immutablevoid** [comment]
Hi, I would like to work on this issue. If you can assign this to me.

**Comment by jeltedeproft** [comment]
@ImmutableBox  sure thing!
